---
- name: netdata basic config
  hosts: "{{ target_hosts | default('all') }}"
  tasks:
    - name: Create a file and write content
      ansible.builtin.template:
        src: /app/ansible/project/templates/netdata.conf.j2
        dest: /etc/netdata/netdata.conf
  # tasks:
  #   - name: Create a file and write content
  #     ansible.builtin.copy:
  #       dest: /etc/netdata/netdata.conf
  #       content: |
  #         [global]
  #           hostname = {{ hostname }}
  #           label = {{ label }}