---
- name: netdata basic config
  hosts: "{{ target_hosts | default('all') }}"
  tasks:
    - name: Create a file and write content
      ansible.builtin.template:
        src: /app/ansible/project/templates/netdata.conf.j2
        dest: /etc/netdata/netdata.conf
      become: true