---
- name: netdata basic config
  hosts: all
  tasks:
    - name: Create a file and write content
      ansible.builtin.copy:
        dest: /etc/netdata/netdata.conf
        content: |
          [global]
            hostname = HOST_NAME
            label = node