---
- name: netdata basic config
  hosts: all

  # tasks:
  # - name: Add HostName

  # tasks:
  # - name: Add Label
  tasks:
    - name: Ensure the directory exists
      ansible.builtin.file:
        path: /path/to/directory
        state: directory
        mode: '0755'
  tasks:
    - name: Create a file and write content
      ansible.builtin.copy:
        dest: /etc/netdata/netdata.conf
        content: |
          [global]
            hostname = HOST_NAME
            label = node