---
- name: netdata basic config
  hosts: all
  become: true

  # tasks:
  # - name: Add HostName

  # tasks:
  # - name: Add Label

- name: Create and write to a file
  hosts: all
  tasks:
    - name: Ensure the directory exists
      ansible.builtin.file:
        path: /etc/netdata/
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Create a file and write content
      ansible.builtin.copy:
        dest: /etc/netdata/netdata.conf
        content: |
          [global]
            hostname = HOST_NAME
            label = node
        owner: root
        group: root
        mode: '0644'
